FROM elixir:1.17-slim

RUN apt-get update && apt-get install -y \
    inotify-tools \
    build-essential \
    git \
    postgresql-client \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN mix local.hex --force && \
    mix local.rebar --force

COPY mix.exs mix.lock ./

RUN mix deps.get

COPY . .

RUN mix do compile

EXPOSE 4000

CMD ["mix", "phx.server"]
